### PR TITLE
CSS Fixes and stuffs

### PR DESCRIPTION
**Pull request by CheaterTim**
finally the inputs are no longer ugly!!!!!!!!!!!!!!

### CODE REVIEW

**Comment by UserUNP** [comment]
issue
image

**Comment by GeorgeRNG** [comment]
image
I don't have that

**Comment by UserUNP** [comment]
> don't have that
you haven't executed the build script

**Comment by UserUNP** [comment]
simple fix: disable the scroll bars on the homepage

**Comment by CheaterTim** [comment]
thats hacky

**Comment by GeorgeRNG** [comment]
I would rather have the site actually fit, I'm not sure what made this happen here.

**Comment by UserUNP** [comment]
try to compare the css between the branches

**Comment by UserUNP** [comment]
@GeorgeRNG @CheaterTim this
image

**Comment by UserUNP** [comment]
changing it to 96% fixes it

**Comment by GeorgeRNG** [comment]
> changing it to 96% fixes it

I just removed the line itself

**Comment by CheaterTim** [comment]
causing the total width to be over 100vw

**Comment by GeorgeRNG** [comment]
You added a width to the header which made everything bigger so I have it removed. I'm also adding some spacing around the cool input elements, thanks for those btw.

**Comment by UserUNP** [comment]
> > changing it to 96% fixes it
> 
> I just removed the line itself

that works too ig

> its probably because some elements have margin/padding

image
it does have padding

**Comment by CheaterTim** [comment]
coping rn

**Comment by CheaterTim** [comment]
I say it was grog's fault

**Comment by UserUNP** [comment]
1. cope
2. mald
3. cry about it

**Comment by UserUNP** [comment]
should probably make the modal padding a little less when on mobile
image

**Comment by CheaterTim** [comment]
> It did start with your change. However I like the buttons and inputs

you put `width: 100;` there!!!!!!!!!!!!

**Comment by GeorgeRNG** [comment]
> > > > It did start with your change. However I like the buttons and inputs
> > > 
> > > 
> > > you put `width: 100;` there!!!!!!!!!!!!
> > 
> > 
> > With that line, it wasn't broke
> 
> it was invalid so I made it valid also ratio

Your validity broke it, at least test what you make.

**Pull request merged**
